apiVersion: v1
kind: pod
matadata:
  name: pod-config
  # Namespace: roboshop
spec:
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerport: 80
    env:
    - name: course
      valuefrom:
        configMapKeyRef:
          name: devops-config
          value: course
---
apiVersion: v1
kind: pod
matadata:
  name: pod-config
  # Namespace: roboshop
spec:
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerport: 80
    envFrom:
    - configMapRef:
        name: devops-config
    